### ISSUE TITLE
Backup overdue when it did run

### ISSUE THREAD

**Issue by Taomyn** [wsj-br/duplistatus#18]
Not sure if this is related to v0.8.21 but I didn't see this last week, but it seems to think this backup is over due when the history shows that it did

<img width="1819" height="759" alt="Image" src="https://github.com/user-attachments/assets/d0b5782b-dc02-4844-9a71-dc58e75621f0" />

All my servers with scheduled backups are set with 3 days for overdue so that it compensates for backups that only run Monday to Friday, such as this one, but so far none of the others set similarly have shown as overdue.

**Comment by rjclarkewp007** [comment]
Hey, i have the same issue. Changed it from 1 days to 24hrs, but still says overdue when it has only been 14hrs since the last backup hehe. Just some timing issue i suppose. :)

<img width="510" height="181" alt="Image" src="https://github.com/user-attachments/assets/29c58421-2837-4f01-a0ce-fb842f5b26bb" />

**Comment by wsj-br** [comment]
Hi Taomyn. It's better to align the schedule you use in Duplicati with Duplistatus, just click on "Collect" button next to the name or use the collect backup logs on the toolbar.  It will update the schedule in Duplistatus and you can use just 1h tolerance. I implemented the same logic used in Duplicati to calculate the next run. 

See this job in Duplicati:

<img width="542" height="566" alt="Image" src="https://github.com/user-attachments/assets/04aa7459-f72a-48ea-872b-2f922aa4f312" />

After the collect (it updated the backup schedule from the duplicati server) it will show in Duplistatus:

<img width="1480" height="86" alt="Image" src="https://github.com/user-attachments/assets/df199a69-0711-4b0f-bbc7-f30851fd2b6a" />

And the Duplicati shows the same time/date for the next run:

<img width="559" height="182" alt="Image" src="https://github.com/user-attachments/assets/3a2d60e3-3e37-4465-b7fe-ff2dd4e0e43e" />

(in the new interface it don't update the next run correctly, probably is a bug).

Please collect the backups using the collect backup logs functionality and check if it's solved.  If not, let me know.

Check the new release too, I just release the v.0.9.0 with user control and audit logs, fix some bugs and done some improvements in the settings page.

**Comment by wsj-br** [comment]
Thank you, that was quick! I will analyse the data now. Regarding NTFY, if the URL is not configured, it will be ignored. If you want a "clean" configuration, go to Settings > Backup Notifications. Click the checkbox on the table header to make disable it for all backups. 

Sorry, I forgot to ask in the previous message. Can you share the screenshot of Settings > Overdue Monitoring too?

**Comment by Taomyn** [comment]
@wsj-br sorry but I've had to disable this feature, with it repeatedly telling me that backups that just run are immediately overdue, yes the job runs and then it tells me the job is overdue, and also it also randomly changing jobs I set the backup interval at 3 days to 1 hour, I'm just getting spammed by it for no reason. I think it's trying to be too clever by calculating things itself.

I also use an old python script called dupReport with a similar feature and it's reporting overdue jobs correctly which is generally zero  except for some manual jobs which I run ad-hoc. I set all scheduled jobs to 3 days so that it covers those jobs that don't run at the weekend, and for others they are either ignored or set to 1 month just to remind me to run them manually.

**Comment by Taomyn** [comment]
@wsj-br I don't think it's fixed yet

<img width="423" height="155" alt="Image" src="https://github.com/user-attachments/assets/ff84352d-9468-414e-9ca2-55d26a23bc92" />

**Comment by Taomyn** [comment]
Output from commands: https://pastebin.com/DFradNT0

**Comment by wsj-br** [comment]
Thank you for the data. I really appreciate it.

I missed one key piece of information: **the backups didn't run on schedule**. With the data you sent, I found the bug and fixed it. The fix will be released in the next version (in a few days).

Also, I added a `Download CSV` button in the **Overdue Monitoring** settings page to extract the debug data if needed (I hope not, as it should be fixed).

**Comment by wsj-br** [comment]
Looks promissing. Thanks for testing it and the suggestion. 

The suggestion is in the TODO for the next version. I didn't notice as I'm using my internal locale (pt_BR) 😎

**Comment by Taomyn** [comment]
Looks like this finally resolved, thank-you
